### ISSUE TITLE
Cannot open PR

### ISSUE THREAD

**Issue by audrius-savickas** [rnw-community/rnw-community#145]
@vitalyiegorov @vitaliiclearmove @habiiev
Hi! I want to use this library, but want to do a few tweaks to its code, specifically - the `react-native-payments` package and open a PR. However, it says that "I don't have permission to push to "rnw-community/rnw-community". Is this a problem on your or my side? Seems like maybe you closed the repo to external pushes? I did create my own branch, so I'm not trying to push to master.

**Comment by vitalyiegorov** [comment]
Good that  you have managed to find a solution! Closing this.
