### ISSUE TITLE
[react-native-payments] Google Pay with Checkout.com error "token_data_invalid"

### ISSUE THREAD

**Issue by audrius-sav** [rnw-community/rnw-community#147]
@vitalyiegorov Hi again!
Google Pay doesn't work with Checkout.com when `signedMessage` is parsed to JS [here](https://github.com/rnw-community/rnw-community/blob/master/packages/react-native-payments/src/class/payment-response/android-payment-response.ts#L57). Checkout.com needs `signedMessage` to be a string, not an object, so when I stringify the `signedMessage` field from Android token, it still doesn't recognize the token. When I remove the `JSON.parse(rawToken.signedMessage) as AndroidSignedMessage`, and then don't stringify it, everything works correctly. I'm guessing that checkout.com is expecting an exactly raw string, not a parsed, then stringified string.

Is there a reason why it is parsed here?

**Comment by vitalyiegorov** [comment]
Could you please show two outputs to compare on the character basis the difference? I mean original and after json.stringify

**Comment by audrius-sav** [comment]
@vitalyiegorov 
These are examples from GPay in test environment, so tokens won't work :)

Raw `singedMessage` field from GPay Android SDK without parsing or stringifying:
```json
{
  "encryptedMessage": "LaU8+f5ka+IYrkagK4K47OcrWu4EBfy77vGFHBy0gk0urMjWA03jHVF/sB5l22wm0FYbar/7wsJp8B0k3ZYo6tBhZrMPaL9H2msR+TONEZdnXx1udggsbLMUSD1JohCakSyQCdjEMygQv0PnD2sp8oGCjC2aHTSbpnP4GarwZOXz08ExuVBbU0753ncp376Nve+zBiCJGDJoXVQr4Qhw9Qf0JmlmTae9Kv1cUG7ah9qBsapgs33MYtdUgVGEoisgcHhDiEEOiDS59Hk9L76quWLiB8KY3Qq7wvfdKbcFF0pXfB/H5ygg1ncnhNsnOatIe5Iu3mpuRPwk0vcfWQWF6/DAo6Zw+och8CRQGBOnwI+G/Q8AY8P8u7JiQhaHXcy1+qolo3IY51nCzciYTt1OKx/k4udQ708mGfXAYIuOt3Y03pw55MTbrq8ZcpsU8z9OccJGhStH039IUlodH5WCUjqBfPTfsgNlEQ\u003d\u003d",
  "ephemeralPublicKey": "BOfl+EvwJSWg6mdFTqZyA0L3VcF03py9nYqIZOqcg1wkgjNW/j0r74pVVMDD8pSOI7IOGA9q/Yz7ZPBZfNjG4OU\u003d",
  "tag": "RDGYe24aMZ/xSPFGXF3ZVRPkF+3fhn/EiuLYeF3VxdA\u003d"
}
```

After `react-native-payments` `JSON.parse()`s it, the JSON becomes:
```json
{
    "encryptedMessage": "LaU8+f5ka+IYrkagK4K47OcrWu4EBfy77vGFHBy0gk0urMjWA03jHVF/sB5l22wm0FYbar/7wsJp8B0k3ZYo6tBhZrMPaL9H2msR+TONEZdnXx1udggsbLMUSD1JohCakSyQCdjEMygQv0PnD2sp8oGCjC2aHTSbpnP4GarwZOXz08ExuVBbU0753ncp376Nve+zBiCJGDJoXVQr4Qhw9Qf0JmlmTae9Kv1cUG7ah9qBsapgs33MYtdUgVGEoisgcHhDiEEOiDS59Hk9L76quWLiB8KY3Qq7wvfdKbcFF0pXfB/H5ygg1ncnhNsnOatIe5Iu3mpuRPwk0vcfWQWF6/DAo6Zw+och8CRQGBOnwI+G/Q8AY8P8u7JiQhaHXcy1+qolo3IY51nCzciYTt1OKx/k4udQ708mGfXAYIuOt3Y03pw55MTbrq8ZcpsU8z9OccJGhStH039IUlodH5WCUjqBfPTfsgNlEQ==",
    "ephemeralPublicKey": "BOfl+EvwJSWg6mdFTqZyA0L3VcF03py9nYqIZOqcg1wkgjNW/j0r74pVVMDD8pSOI7IOGA9q/Yz7ZPBZfNjG4OU=",
    "tag": "RDGYe24aMZ/xSPFGXF3ZVRPkF+3fhn/EiuLYeF3VxdA="
  }
```

The main difference that I see is that GPay returns "equals" symbol (=) as unicode char ("\u003d"). Then `JSON.parse()` parses it into an actual equals sign (=). And then when stringifying it again, it's still left as an equals sign (=).
So in the end, the token returned from GPay SDK and the one sent to server differ and that's probably why it fails.

So I think that adding `rawSignedMessage` field would work, but maybe `rawToken` would work even better. It would hold the whole non-parsed GPay token, not only `signedMessage` field.

**Comment by filippobarcellos** [comment]
The same thing is happening to me.

"signature" prop gets a = signal attached at the end.

Any way to solve it?

Thanks

Valid token

`{"signature":"MEYCIQCuRhDFy5mMzlPYFT0rDPe4LhYcNEqizOPLivQufxiNKgIhALJzxbdxPyz6krRxAjXPBc3U3Hl6YuZWDvZhMM9XqJdt","protocolVersion":"ECv1","signedMessage":"{\"encryptedMessage\":\"TlT6ZECX3LA/bMiHYQN/dWsSHfilUUkNeKnWZHfY47XkXIEQoPqhjg0Ts8E6SJk1c8NK1ROBWUzKBA7cMbpZTXo+rAt4h0YXolrLUE5LfcVnUQRKjBJ3KLcZjhB8P83dRZjnhHTG7Eo+YIHmPZPSi4YwHCP5z9eq4EkPPEyocKg+WdSSEox6gEwRUuYO78ehMwoHQqSNiH4YCV3dxgKEetfMrJqF3nlRSwX/llQ3q2/UZOiEX9KNrsu5pd3CXnMBX6Vmt7wEby+o9a+XtwuHRAxzP6M1jl1L9M+RSeAnbe/yKnzRH8/tbgTO9fekBWler/44UY5Q127L+r/1lvDUtuuATUZWQPFXUWaN46cZQoTy8XQPBbciwu0gncfIbjDXh++TMoKJNEYr43MSOl19W5WtYtzf4+xGJjyIPKklgciHSetlRwiwrbXbdVkDVgodcDtbJP/AbkE2DJ9i2dBiohmQSzi8E0AV+wbSHiET0N8Wu0y/JX1L5uSLVF+OyGU1Wzv40P7WrXjcSvErLsX9X7Nm0bWx3MgRdeVu03CVCKU8QHFNNWzT\",\"ephemeralPublicKey\":\"BC52d6btsSQpB6knNnVIpUl/bc24uJbpUb08oA2nMCPXYETpkzUQIjF145+lfGxII9m5Jql7t7vD16Nl7Bs0OdA\\u003d\",\"tag\":\"yUCeJAz1prlWdM3OuG0bgEkrwp2d2lgHg/aozvi+pq4\\u003d\"}"}`

Failed token
`{"protocolVersion": "ECv1", "signature": "MEUCIF0k6iwA/kGbYVa7cndAx63tmvYs6rACvbXWFHAAcuYKAiEAsmUW4jtl/vIhha3IE2tP6tSWQtWO8HfWrjEJRVfbUmQ=", "signedMessage": "{\"encryptedMessage\":\"QN7kDIvuKHd8/WOg9Aqm+FJJEJ2iVkg/ZEgs75POeNskmG5TdUFzHgNQIZj6CODzMOZlyI5fjStJyVu+fq1Z+a2edAMLOoTsASQp9UdXR2IfhZbxNPCUIyxpz7ZJ6qLkWmhIxw8BmJxaEVWeadv2htdco+Nx7mtyQ3CCZtt8In5YnsdjFYeThIGua9b6daatOURnVvUJLhnG+XNMcPXQ2koyy7AGOjvk3aFHeWzP17vv0W94BnTNjQ1XAuNL5SwV3FXCI4wfwAI5AATVsLDlOPtje7Q4I4eRyfhKZkzU7OgUbcs4jHqZt+2oo8TOIwBBaZSjqk/7NbI9lGhWIbOaOQmfqUs6Zd5k/qQxAKuLBUrabTUGdEXORY3jffsMtTvrDCIa5Ck6xS97OLKdJUSEDEpN+jGnZMDpDkLApTQTjBm4QA4lu1dNqdAifwXynJDyuVHgjk9ZBTpXqQp3A3R0juTOXU4dJY3WfDZvoEwfVW/XyxqphdY+moRTbFA+Hrm8TpCv5nNm9rq2fPblMv/y6Uiu08R8QntcQ9UdxCjsGJcVyUIpDTWWNs0kfJwX49KPH7CXJgP+wRQZUuSl\",\"ephemeralPublicKey\":\"BIZaFqOoXRVHpoxe0RYCQZJgBlVILsqjfHLDYkb/zNUSTR2Q7dRW3q9R/zcTSrJiMV3MclCFY7RvHO+0d93hms4\\u003d\",\"tag\":\"XJ0qSSXY/m1J04IIhumGakUdt4IdkBbF9g9wOnY1ze0\\u003d\"}"}`

**Comment by vitalyiegorov** [comment]
thanks for the information, #149 will fix it, please use new `rawToken` field for the android.
Waiting for your feedback! Btw are you using this lib in production? Could you please describe your use case and what payment gate are you using, we plan to add supported payment gates to the docs for other users.

**Comment by filippobarcellos** [comment]
Hi @vitalyiegorov I'm using WorldPay as a payment gate. I tried the fix on a local branch and doesn't seem to be fixed. Any chance I might be doing something wrong by adding my own merchant?

**Comment by vitalyiegorov** [comment]
Have you tried using new rawToken field for sending to the WorldPay? Can
you provide a docs link so I can help?

пт, 13 жовт. 2023 р. о 18:19 Filippo Barcellos ***@***.***>
пише:

**Comment by vitalyiegorov** [comment]
@filippobarcellos As this issue is closed, could you please create a new one with the proper description and title
