### ISSUE TITLE
[react-native-payments] [!] Invalid `Podfile` file: source is not valid JSON!.

### ISSUE THREAD

**Issue by younisrahman** [rnw-community/rnw-community#163]
### When I try to install pod, this error is showing up.

```
error Failed to build the app: No package name found. Found errors in /Volumes/FilePath/node_modules/@rnw-community/react-native-payments/android/src/main/AndroidManifest.xml.

[!] Invalid `Podfile` file: source is not valid JSON!.

 #  from /Volumes/FilePath/ios/Podfile:9
 #  -------------------------------------------
 #  target 'AppName' do
 >    config = use_native_modules!
 #  
 #  -------------------------------------------

```

### In what environment did this happen?
React Native version:  "0.70.6",
Node version: v16.20.0,
React Native Payment: "@rnw-community/react-native-payments": "^0.62.2"

**Comment by vitalyiegorov** [comment]
@younisrahman You have an error in the `/Volumes/FilePath/node_modules/@rnw-community/react-native-payments/android/src/main/AndroidManifest.xml.` 
But why it references IOS pod file?

**Comment by vitalyiegorov** [comment]
Closing as there were no answer from @younisrahman

**Comment by Sulaiman122** [comment]
faced closed to this issue
` #  from /Volumes/FilePath/ios/Podfile:9
 #  -------------------------------------------
 #  target 'AppName' do
 >    config = use_native_modules!
`

issue for me was node 14 change to 18 then it work now
