### ISSUE TITLE
[react-native-payments] not working with expo prebuild

### ISSUE THREAD

**Issue by informsharique** [rnw-community/rnw-community#170]
I was trying to install this library using expo prebuild. But I was getting this error
```
⚠️  ld: Could not find or use auto-linked framework 'CoreAudioTypes'
❌  Undefined symbols for architecture x86_64
┌─ Symbol: _OBJC_CLASS_$_PKPaymentAuthorizationResult
└─ Referenced from: objc-class-ref in react_native_payments(Payments.o)
```
I think this maybe due to the **import** requirement in the **AppDelegate.h**. Generally prebuild works fine with any package as long as it supports autolinking. Does this package support autolinking? If not, what can be done to avoid the issue?

I was using this package before and it was working fine. Just 3-4 days back I started getting this issue, not sure what causing this.

**Comment by vitalyiegorov** [comment]
@informsharique Maybe this is related to the recent Xcode updates? 

Which version are you using? 
https://developer.apple.com/forums/thread/736152

Or a react-native-flipper issue? 
https://github.com/facebook/metro/issues/1121

We have not made any changes recently so this issue probably is not related to this lib

**Comment by informsharique** [comment]
@vitalyiegorov Thanks for your response and looking into the issue.

> Which version are you using?

I'm using Xcode 15.0

> Or a react-native-flipper issue?

I'm not using react-native-flipper and in the metro link you provided, there someone suggested a workaround. I tried that but its still giving the same error.

> We have not made any changes recently so this issue probably is not related to this lib

Yes I noticed since we got the error with the version that was working fine before. But as soon as I remove this lib... build started working fine and when I add it back I see this error. Maybe something is being used in this library thats making it incompatible with the Xcode version to compile??

Also, one thing to note here is on the apple developer forum, I saw this is due to `❌  Undefined symbols for architecture x86_64` this error and not the `CoreAudioType`.

**Comment by vitalyiegorov** [comment]
@informsharique have you succeeded with the issue? Can you give any update?

Btw, adding expo module support is very important part of this repo todo

**Comment by vitalyiegorov** [comment]
Closing as there were no answer from @informsharique

**Comment by informsharique** [comment]
@vitalyiegorov I was a bit busy but I have tested it multiple times with different react native and expo versions and still getting the same result again and again. I am attaching the screenshot of the error here. Wherever I remove this package the app builds fine but as soon as I update it, the error is the same and it refers to react_native_payments Payment.o

<img width="744" alt="image" src="https://github.com/rnw-community/rnw-community/assets/13877461/ca82322a-48be-47ba-97fb-0ee2d877f6bd">
