### ISSUE TITLE
[react-native-payments] Jest tests failing

### ISSUE THREAD

**Issue by mark-quinn** [rnw-community/rnw-community#173]
After migrating from [react-native-payments](https://github.com/naoufal/react-native-payments), the last issue I have is around the jest setup.

I have tried mocking it with `jest.requireActual` but it appears to be failing due to something related to the TurboModule setup.

The error I am getting is: `Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'Payments' could not be found. Verify that a module by this name is registered in the native binary.`. I can see that the 'Payments' reference is here in this packages file [here](https://github.com/rnw-community/rnw-community/blob/master/packages/react-native-payments/src/NativePayments.ts).

Any advice on how to mock this would be helpful.

**Comment by vitalyiegorov** [comment]
Hi, I could help you if you will provide a repo that is reproducing the issue, how do you mock and what exactly?

**Comment by mark-quinn** [comment]
> Hi, I could help you if you will provide a repo that is reproducing the issue, how do you mock and what exactly?

Hi @vitalyiegorov, won't be able to provide a repo since it's private. Sorry for some more context, we upgraded to this package and when we did the unit tests started to fail. The error we were getting was relating to the Turbo repo module error as shown above.

Our current solution to fix these errors was to mock this module in the `jest.setup.js` file like so:

```js
jest.mock('@rnw-community/react-native-payments', () => {
  return {
    canMakePayments: jest.fn(),
    requestPayment: jest.fn(),
    PaymentMethodNameEnum: {
      AndroidPay: 'android-pay',
      ApplePay: 'apple-pay',
    },
    IosPKMerchantCapability: {
      PKMerchantCapability3DS: 'PKMerchantCapability3DS',
      PKMerchantCapabilityCredit: 'PKMerchantCapabilityCredit',
      PKMerchantCapabilityDebit: 'PKMerchantCapabilityDebit',
      PKMerchantCapabilityEMV: 'PKMerchantCapabilityEMV',
      PKMerchantCapabilityInstantFundsOut:
        'PKMerchantCapabilityInstantFundsOut',
    },
    SupportedNetworkEnum: {
      Amex: 'amex',
      Mastercard: 'masterCard',
      Visa: 'visa',
    },
  };
});
```

Happy to close this issue as we managed to sort this out but it would be good for the recommended jest setup to be included to the repo ?

**Comment by vitalyiegorov** [comment]
Thanks that you have provided a solution, a pr with the readme update would be useful.

I have a question, why did you mock the enums also? Can you use the ...jest.requireActual approach and kick only behavior?

**Comment by vitalyiegorov** [comment]
You can start with mocking only RN turbo module and try, and if needed then mock the library itself
```ts
jest.mock('react-native', () => ({
    ...jest.requireActual('react-native'),
    TurboModuleRegistry: {
        getEnforcing: jest.fn(),
    },
}));

const mockReactNativePayments = jest.mock('@rnw-community/react-native-payments', () => ({
    ...jest.requireActual('@rnw-community/react-native-payments'),
    PaymentRequest: {
        canMakePayments: jest.fn(),
        abort: jest.fn(),
        show: jest.fn(),
        requestPayment: jest.fn(),
    },
    PaymentResponse: {
        complete: jest.fn(),
        retry: jest.fn(),
    },
}));

```

**Comment by mark-quinn** [comment]
> You can start with mocking only RN turbo module and try, and if needed then mock the library itself
> 
> ```ts
> jest.mock('react-native', () => ({
>     ...jest.requireActual('react-native'),
>     TurboModuleRegistry: {
>         getEnforcing: jest.fn(),
>     },
> }));
> 
> const mockReactNativePayments = jest.mock('@rnw-community/react-native-payments', () => ({
>     ...jest.requireActual('@rnw-community/react-native-payments'),
>     PaymentRequest: {
>         canMakePayments: jest.fn(),
>         abort: jest.fn(),
>         show: jest.fn(),
>         requestPayment: jest.fn(),
>     },
>     PaymentResponse: {
>         complete: jest.fn(),
>         retry: jest.fn(),
>     },
> }));
> ```

I get other errors when I use this method. I am assuming other modules must have a dependency on the turbo module registry implementation. I get: `Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'SettingsManager' could not be found`. The only working method I found was the mock I used

**Comment by vitalyiegorov** [comment]
According to the error that you have provided the mock did not work, as it shows that the original `TurboModuleRegistry.getEnforcing` was called, can you please provide a reproduction of your test?

**Comment by vitalyiegorov** [comment]
No activy, closing for now
