### ISSUE TITLE
Error iOS building Undefined symbol:PKPaymentAuthorizationResult

### ISSUE THREAD

**Issue by Sulaiman122** [rnw-community/rnw-community#179]
Hello
appreciate your work on this library

Tried the following:
npm install @rnw-community/react-native-payments
cd ios && pod install

Im getting this issue when building the project
`Undefined symbol: _OBJC_CLASS_$_PKPaymentAuthorizationResult`

"@rnw-community/react-native-payments": "^0.65.5",
"react": "18.2.0",
"react-native": "0.72.7"
Node: 18.17

Have no clue why, maybe it's roseta(new arcetcure) tried to convert to silicon, and seems the same
Also tried to reset cache for metro
and cleaning build folder
and removing derived data

![Screenshot 2024-02-14 at 2 39 05 PM](https://github.com/rnw-community/rnw-community/assets/33493055/bec9f14e-52b6-4761-86a3-567838c7136a)

**Comment by vitalyiegorov** [comment]
Hi @Sulaiman122 have you followed this guide to add support for the Apple Pay to your app https://developer.apple.com/library/archive/ApplePay_Guide/Configuration.html ?

**Comment by Sulaiman122** [comment]
I believe i did.
I no longer need this package
Thank you for your contribution🌹
