### ISSUE TITLE
warn Package @rnw-community/react-native-payments has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports" in ....

### ISSUE THREAD

**Issue by fcbjimmy** [rnw-community/rnw-community#182]
Hello Mr Vitaly

I got the below error after installing @rnw-community/react-native-payments@0.65.5. 
Using 0.65.5 because my project must use node version 16.19.0 and the latest version requires node>=18.

So after the installation and I tried running metro the below happens:

![image](https://github.com/rnw-community/rnw-community/assets/86477137/9c9dbe0e-32d0-496a-8dfc-057714c6cfb6)

The errors:
warn Package @rnw-community/react-native-payments has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports" in ....

warn Package react-native-screens has been ignored because it contains invalid configuration. Reason: "dependency.platforms.android.componentDescriptors" is not allowed

For your reference:
"react": "17.0.2",
"react-native": "0.67.5",
"@rnw-community/react-native-payments": "0.65.5",
"react-native-screens": "^3.12.0"

**Comment by vitalyiegorov** [comment]
@fcbjimmy Did you fix a problem? Can I still help you?
