### ISSUE TITLE
@rnw-community/nestjs-webpack-swc@^0.67.0: Doesn't generate source maps even if manually instructed to do so

### ISSUE THREAD

**Issue by Crismon96** [rnw-community/rnw-community#188]
Great, plugin! It really provides good presets and made the otherwise complicated setup pretty easy.
I have 2 concern primarily:
1. The plugin doesn't allow me to specify swc-loader options directly. From the library I can not import any of the underlying web pack configs to create my own from them, nor can I pass `swcOptions` to the development or prod web pack config.
2. The problem I want to address here today. Even if I hardcode the `sourceMaps` option to true or "inline" in the base-config no source maps are generated. When I log the resulting webpack config I can see that my override is actually applied:
```
{
  entry: ['webpack/hot/poll?100', '/Users/christophgriehl/code/predium/apps/backend/src/main.ts'],
  devtool: false,
  target: 'node',
  output: { filename: 'main.js' },
  ignoreWarnings: [{}],
  externals: [null],
  externalsPresets: { node: true },
  module: {
    rules: [
      {
        test: {},
        use: {
          loader: 'swc-loader',
          options: {
            sourceMaps: true,
            module: { type: 'commonjs', strict: true },
            jsc: {
              target: 'es2020',
              parser: { syntax: 'typescript', decorators: true },
              transform: { legacyDecorator: true, decoratorMetadata: true },
              keepClassNames: true,
            },
          },
        },
        exclude: {},
      },
    ],
  },
  resolve: {
    extensions: ['.tsx', '.ts', '.js'],
    plugins: [
      {
        source: 'described-resolve',
        target: 'resolve',
        extensions: ['.ts', '.tsx'],
        referenceMatchMap: {},
        log: {},
        baseUrl: './',
        absoluteBaseUrl: '/Users/christophgriehl/code/predium/apps/backend',
      },
    ],
  },
  mode: 'none',
  optimization: { nodeEnv: false },
  node: { __dirname: false, __filename: false },
  plugins: [
    { options: {} },
    { options: {} },
    { paths: [{}, {}] },
    { options: { autoRestart: false, signal: false, keyboard: false, name: 'main.js', args: [], nodeArgs: [] } },
  ],
  cache: {
    type: 'filesystem',
    cacheDirectory: '/Users/christophgriehl/code/predium/apps/backend/.build_cache',
    allowCollectingMemory: true,
  },
};
```

but I can find no sourceMaps in my dist. Also generating inline sourceMaps doesn't work.

I have found no information that creating source maps with swc-loader isn't supported nor can I find other bug reports. I currently managed to create sourceMaps by web pack itself via `devtools: source-map` but the line numbers in the source map seem to be off. Can you maybe provide a hint how I can generate a valid source map for my swc compiled bundle please.

**Comment by vitalyiegorov** [comment]
Thanks for the feedback! Recent versions on NestJS have a built in support for the SWC so this library is deprecated, I highly encourage you to try it: https://docs.nestjs.com/recipes/swc
