### ISSUE TITLE
Error for Mada Support still exists

### ISSUE THREAD

**Issue by AhmedHashem2105** [rnw-community/rnw-community#200]
<img width="560" alt="Screenshot 2024-06-12 at 2 57 43 AM" src="https://github.com/rnw-community/rnw-community/assets/146625516/8b01a856-688d-4764-91bf-ae2fea304005">

show(): Promise<AndroidPaymentResponse | IosPaymentResponse> {
        return new Promise<AndroidPaymentResponse | IosPaymentResponse>((resolve, reject) => {
            this.acceptPromiseRejecter = reject;

            if (this.state === 'created') {
                this.state = 'interactive';

                // HINT: We need to pass Android environment configuration to native module via details
                const details = isAndroid
                    ? {
                          ...this.details,
                          environment: (this.platformMethodData as AndroidPaymentMethodDataDataInterface).environment,
                      }
                    : this.details;

                NativePayments.show(this.serializedMethodData, details)
                    .then(jsonDetails => {
                        resolve(this.handleAccept(jsonDetails));

                        return void 0;
                    })
                    .catch((err) => console.log(err));
            } else {
                reject(new DOMException(PaymentsErrorEnum.InvalidStateError));
            }
        });
    }
    
    when i console.log(err) in NativePayments, i gives the screenshot in console

**Comment by vitalyiegorov** [comment]
@AhmedHashem2105 Please test the latest version 0.72.0 https://www.npmjs.com/package/@rnw-community/react-native-payments and reopen if needed

**Comment by AhmedHashem2105** [comment]
It worked.
Thank you very much

Regards
Ahmed Hashem
