### ISSUE TITLE
.show() opens and closes immediately

### ISSUE THREAD

**Issue by abffit** [rnw-community/rnw-community#207]
I have tried to integrate the Apple Pay by using '@rnw-community/react-native-payments' package. I have followed all the steps and was able to integrate the Apple Pay. The .show() method was working fine for me for the time alone. If I try to call .show() for the second time, it opens and closes immediately. I am not able to get the error log also. Can you anybody guide me how to resolve the issue?

Thanks in advance!

**Comment by TheAhmadSami** [comment]
Did you find a solution for this?

**Comment by SYursa** [comment]
So, I’ve resolved my issue. On version 1.2.0, it would close immediately — the sound didn’t even have time to finish. After downgrading to version 1.1.0, everything works fine and displays correctly. My environment is Expo version 52. @vitalyiegorov, please take note of this.
