### ISSUE TITLE
Getting blank values from ApplePayToken Payment Data

### ISSUE THREAD

**Issue by dhave-bp** [rnw-community/rnw-community#210]
Hi, I would like to get some help on implementing Apple Pay in our react native app. Currently we are using v0.64.0. When trying to simulate the payment in a simulator we are getting blank values 

IOS Payment Method Setup:
export const IosMethodData: IosPaymentMethodDataInterface =
  // ApplePay
  {
    supportedMethods: PaymentMethodNameEnum.ApplePay,
    data: {
      merchantIdentifier: Config.APPLE_PAY_MERCHANT_ID,
      supportedNetworks: [SupportedNetworkEnum.Visa, SupportedNetworkEnum.Mastercard],
      countryCode: DEFAULT_USER_COUNTRY,
      currencyCode: DEFAULT_USER_CURRENCY,
      requestBilling: false,
      requestEmail: false,
      requestShipping: false,
    },
  };
  
  ApplePayToken Payment Data we are getting:
  {"data": "", "header": {"applicationData": "", "ephemeralPublicKey": "", "publicKeyHash": "", "transactionId": "", "wrappedKey": ""}, "signature": "", "version": ""}
  
  Hope to get help from anyone thanks!

**Comment by takawww** [comment]
Hi, I am having an exactly the same issue. how could you fix it?
