### ISSUE TITLE
react-native-payments: displayItems should be optional

### ISSUE THREAD

**Issue by arturybak** [rnw-community/rnw-community#217]
The standard mentions that `displayItems` property of `details` is not required, but it's not optional in `react-native-payments/dist/esm/@standard/w3c/payment-details-base.d.ts`:

```
export interface PaymentDetailsBase {
    displayItems: PaymentItem[];
    modifiers?: PaymentDetailsModifier[];
}
```

**Comment by vitalyiegorov** [comment]
Thanks for the feedback, can you please provide a reference to the standard and a PR with the improvement?
