### ISSUE TITLE
Allow for optional requiredShippingContactFields

### ISSUE THREAD

**Issue by KrastanD** [rnw-community/rnw-community#228]
As we know from [the docs](https://developer.apple.com/documentation/passkit_apple_pay_and_wallet/pkpaymentrequest/1619221-billingcontact) it's only possible to get back the postalAddress from the `requiredBillingContactFields`. If you want any of the other fields, such as name, email, and phone, you need to get them back from the `requiredShippingContactFields`. 

The issue is that I don't want to ask the user for the shipping address because they won't be shipped anything. I do, however, want their contact information. This can be achieved on the native side by removing `PKContactFieldPostalAddress` from `requiredShippingContactFields`. 

There's a few ways the js api can be extended to support this. 
1.  Split the current `requestShipping` into `requestShippingContactInfo` and `requestShippingAddress`. This would be a breaking change. 
2. Do the above but keep `requestShipping` for backwards compatibility which sets both `requestShippingContactInfo` and `requestShippingAddress` to true. No breaking change. 
3. Keep `requestShipping` and add `noShippingAddress`. No breaking change. 
4. Make `requestShipping` an object where you can specify which fields you want. Breaking change but more future proof.

Let me know your thoughts. I'd be happy to submit a PR with whatever path makes sense. 
Thank you!

**Comment by vitalyiegorov** [comment]
This library supports both IOS and Android, and the JS layer has a generic approach bot mapping and normalizing the behaviour, I have added all the references in the code to the official docs of the above mentioned platforms, so we need to analyze such changes in scope of two worlds and also stay as compliant as possible with the [W3C](https://www.w3.org/TR/payment-request/#dom-paymentoptions). 

We do have a [roadmap item](https://github.com/rnw-community/rnw-community/blob/master/packages/react-native-payments/readme.md#todo) for improving the shipping options, maybe we can go further into [this direction](https://www.w3.org/TR/payment-request/#shippingoption-attribute).  

I would start with understanding `How can we achieve the same behaviour on the Android`?  `Does W3C(browser) supports this and how to achieve it there?`

**Comment by KrastanD** [comment]
**How can we achieve the same behavior on the Android?**
On Android, the [payment data response contains the email if `emailRequired` is passed in the request](https://developers.google.com/pay/api/android/reference/response-objects#PaymentData), and [the name and phone number come from the billing address if `billingRequired` is passed to the request](https://developers.google.com/pay/api/android/reference/response-objects#CardInfo)

**Does W3C(browser) supports this and how to achieve it there?**
[W3C has `requestPayerEmail`, `requestPayerName`,  and `requestPayerPhone`. ](https://www.w3.org/TR/payment-request/#dom-paymentoptions)We can extend the `GenericPaymentMethodDataDataInterface` and add `requestPayerName`, and `requestPayerPhone`. To support that on iOS, under the hood we'll use `requestShippingContactInfo` and only add the PKContactFields the user asked for. And on Android we can just get them from the billingAddress.
