### ISSUE TITLE
Error: [ReactNativePayments] [DOMException]

### ISSUE THREAD

**Issue by denysoleksiienko** [rnw-community/rnw-community#233]
When close the payment sheet and open it again, an error appears.
If a user has canceled a payment, he can't open it again to continue?

```
 ERROR  [Error: Payment process canceled by user.]
 ERROR  [Error: [ReactNativePayments] [DOMException]: The object is in an invalid state.]
```

**Comment by vitalyiegorov** [comment]
Can you please provide a repo with the reproduction?

**Comment by denysoleksiienko** [comment]
@vitalyiegorov 
Here is a reproducible repo https://github.com/denysoleksiienko/rn_payments_setup.
Also, I attached an error video. It doesn't matter, ios or android, the error same when canceling the payment and then trying to pay again

**Comment by vitalyiegorov** [comment]
can you please try the recent react-native-payments-example package  and
record a video with it?

пт, 1 лист. 2024 р. о 13:20 Denys Oleksiienko ***@***.***>
пише:

**Comment by denysoleksiienko** [comment]
@vitalyiegorov Sorry, my mistake. All work fine. Thanks
