### ISSUE TITLE
[react-native-payments] Android config

### ISSUE THREAD

**Issue by denysoleksiienko** [rnw-community/rnw-community#235]
I have some questions about the Android payment config.

1. How do I set up the API version based on the tutorial? https://developers.google.com/pay/api/android/guides/tutorial#api-version
```
API = {
 apiVersion: 2,
 apiVersionMinor: 0
}
```

2. Set allowedPaymentMethods (type, tokenizationSpecification type, merchantInfo and transactionInfo). https://developers.google.com/pay/api/android/guides/tutorial#payment-data-request
The final config should be like this:
```
const paymentRequest = {
  apiVersion: 2,
  apiVersionMinor: 0,
  allowedPaymentMethods: [
    {
      type: 'CARD',
      parameters: {
        allowedAuthMethods: ['PAN_ONLY', 'CRYPTOGRAM_3DS'],
        allowedCardNetworks: ['MASTERCARD', 'VISA'],
      },
      tokenizationSpecification: {
        type: 'PAYMENT_GATEWAY',
        parameters: {
          gatewayMerchantId: 'gatewayMerchantId',
          gateway: 'gateway',
        },
      },
    },
  ],
  merchantInfo: {
    merchantId: 'merchantId',
    merchantName: 'merchantName',
  },
  transactionInfo: {
    totalPriceStatus: 'FINAL',
    totalPriceLabel: 'Total',
    totalPrice: 10,
    currencyCode: 'USD',
    countryCode: 'US',
  },
};
```

**Comment by vitalyiegorov** [comment]
@denysoleksiienko Please take a look into the [example app](https://github.com/rnw-community/rnw-community/tree/master/packages/react-native-payments-example) 

Have you followed the [Installation guide](https://github.com/rnw-community/rnw-community/tree/master/packages/react-native-payments#installation)

What problems are you facing?

**Comment by chetanbhadarka** [comment]
@denysoleksiienko How did you able to set the apiVersion: 2 for Google Pay?
