### ISSUE TITLE
ApplePay Crash

### ISSUE THREAD

**Issue by Abdulmalick-Dimnang** [rnw-community/rnw-community#236]
Hi, I'm experiencing an inconsistent crashes that occurs after confirming an Apple payment (wheither, it's Face ID or PassCode) and this crash happens from time to time

I'm using Sentry and here's the following error that i'm getting

![Screenshot 2024-10-09 at 6 41 12 PM](https://github.com/user-attachments/assets/b10a2f63-b5b8-4b99-95ce-75b8b655f6fe)

Since this crash relates to memory issues, would it be somehow related to this package since it happens on ApplePay

Would appreciate your feedback 🙏 

package.json:
```
"react-native": "0.74.5",
"@rnw-community/react-native-payments": "0.74.0",
```

P.S.
- Hermes is enabled on iOS
- New arch is turned off

**Comment by vitalyiegorov** [comment]
Thanks for the report @Abdulmalick-Dimnang , to help you we need a reproduction repository/fork, 

also please check [example app](https://github.com/rnw-community/rnw-community/tree/master/packages/react-native-payments-example) if you will have the same

**Comment by vitalyiegorov** [comment]
@Abdulmalick-Dimnang Have you tried? Otherwise I will close this issue

**Comment by Abdulmalick-Dimnang** [comment]
hey @vitalyiegorov 

Honestly, it's really hard to replicate it since it never happened to me once but I see it happened to a lot of users through Sentry and other reports from end users

So I decided to not use the package unfortunately and instead I had to write a custom module to handle only ApplePay and that worked out so far

**Comment by vitalyiegorov** [comment]
@Abdulmalick-Dimnang Thanks for the feedback, i will try to analyze the error you have provided during the swift migration.

**Comment by vitalyiegorov** [comment]
Please try https://github.com/rnw-community/rnw-community/releases/tag/v0.77.0
