### ISSUE TITLE
[react-native-payments] Android response doen't return info about card

### ISSUE THREAD

**Issue by denysoleksiienko** [rnw-community/rnw-community#240]
Since Google Pay API version 2.0 can show the card details in response. 
How do I get the info card (network and 4 digits) with `react-native-payments`?

https://developers.google.com/pay/api/android/reference/response-objects#PaymentData
https://developers.google.com/pay/api/android/reference/response-objects#CardInfo

**Comment by denysoleksiienko** [comment]
@vitalyiegorov Hello.
It looks like the `AndroidPaymentMethodData` with `info: AndroidCardInfo` or just `AndroidCardInfo` is not parsed in the AndroidPaymentResponse, am I right? Please, could you check?
https://github.com/rnw-community/rnw-community/blob/master/packages/react-native-payments/src/%40standard/android/response/android-payment-method-data.ts
https://github.com/rnw-community/rnw-community/blob/master/packages/react-native-payments/src/class/payment-response/android-payment-response.ts

**Comment by vitalyiegorov** [comment]
@denysoleksiienko Can you please provide a Pull request with a potential fix?

**Comment by denysoleksiienko** [comment]
@vitalyiegorov I'm not sure how it should be correctly. I created a path with an example of potential code. Please check
[Return_cardInfo_for_Android_response.patch](https://github.com/user-attachments/files/17590142/Return_cardInfo_for_Android_response.patch)

**Comment by vitalyiegorov** [comment]
@denysoleksiienko I have created a pull request #246 from your patch for you, now we can analyze the changes and improve, can you please show me where do you get the card info data on IOS response?

**Comment by denysoleksiienko** [comment]
@vitalyiegorov card info on ios response comes from `applePayToken: IosPaymentResponse.parsePkToken(data.token)`
Here is my response:
`{"paymentMethod": {"network":"Visa","type":"PKPaymentMethodTypeCredit","displayName":"Visa 0101"}, "transactionIdentifier": ".......", "paymentData": {"data": "......"}`

https://github.com/rnw-community/rnw-community/blob/master/packages/react-native-payments/src/%40standard/ios/response/ios-pk-token.ts

**Comment by vitalyiegorov** [comment]
fixed in https://github.com/rnw-community/rnw-community/releases/tag/v0.77.0 please check

**Comment by denysoleksiienko** [comment]
@vitalyiegorov Yes, it works in `0.77.0`, and see card details in the response. Thank you
