### ISSUE TITLE
Google Pay canMakePayments hard-coded to TEST

### ISSUE THREAD

**Issue by pdaplyn** [rnw-community/rnw-community#259]
Hi,

I notice that the Android `canMakePayments` method is hard-coded to use `ENVIRONMENT_TEST` rather than the environment configured via `PaymentMethodData`.

https://github.com/rnw-community/rnw-community/blob/master/packages/react-native-payments/android/src/main/java/com/payments/PaymentsModule.java#L110

Is this deliberate?

Thanks.

**Comment by vitalyiegorov** [comment]
@pdaplyn Wow, good catch! Of course not and it is weird that no one noticed it before, i will create a PR for this.
