### ISSUE TITLE
Get information when the dialog opens up?

### ISSUE THREAD

**Issue by ShooterArk** [rnw-community/rnw-community#260]
Hi there, I have integrated the plugin and its working well but now I need to get the information when the payment dialog (Apple Pay or Google Pay) appears. The objective is to get the shipping address from the dialog, send it to the server to calculate the tax and update the information back to the dialog before user completes the payment.

Is that possible?

Please advise. 
Thank you.

**Comment by vitalyiegorov** [comment]
Hi @ShooterArk, thanks for using this library

This dialog does not process a payment, your backend should, and that is where you can check the shipping and billing information.

**Comment by ShooterArk** [comment]
@vitalyiegorov I may have not explained it properly, but the problem was never to process the payment but to get the shipping from the dialog itself, which I have already achieved :). 
Thank you.
